FROM golang:1.22 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG SERVICE
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/service ./cmd/${SERVICE}

FROM gcr.io/distroless/static-debian12
COPY --from=build /bin/service /app/service
WORKDIR /app
COPY keys ./keys
ENTRYPOINT ["/app/service"]
