global:
  scrape_interval: 5s
  scrape_timeout: 3s
scrape_configs:
  - job_name: gateway
    static_configs: [{targets: ['gateway-api:8080']}]
  - job_name: aggregator
    static_configs: [{targets: ['aggregator:8081']}]
  - job_name: features
    static_configs: [{targets: ['features:8082']}]
  - job_name: alerts
    static_configs: [{targets: ['alerts:8083']}]
  - job_name: governance
    static_configs: [{targets: ['governance:8084']}]
  - job_name: query
    static_configs: [{targets: ['query:8085']}]
  - job_name: inference
    static_configs: [{targets: ['inference:8090']}]
